Added second assignment
galeal2/CodeU pull request #3
Opened 2017-05-29 10:27 UTC by galeal2

1) Find all ancestors of a key in a Binary Tree.
2) Find the lowest common ancestors of 2 nodes.

2017-05-30 17:57 UTC, ariava requested changes
Great job with the testing!

2017-05-30 17:57 UTC, ariava commented on assignment_2_Q2.py
> +class Node:
Can you try to group the common classes in a separate library, or use assignment_2_Q1.py as a library for assignment_1_Q2.py, as you prefer? In this way you ensure that your code is what is called a "single point of truth". For example, let's say you find a bug in the BST class while you are coding the Q2 file. You must remember afterwards to replicate the fix in the Q1 file. If you avoid duplication of the code it's easier, there is only one point to change.

2017-05-30 17:57 UTC, ariava commented on assignment_2_Q1.py
> +def rec_find_ancestors(ptr, key, path):
What does "rec" stand for? Could you please use a more obvious term for the slow readers like me, or explain in a comment?

Also, can you write a short docstring that explains what the parameters are for?

2017-05-30 17:57 UTC, ariava commented on assignment_2_Q1.py
> +        self.item = item
This is just a nit: wouldn't it be clearer to call it "key"?

2017-05-30 17:57 UTC, ariava commented on assignment_2_Q1.py
> +    tree = BST([16, 9, 18, 3, 14, 19, 1, 5])
Great job with testing!

2017-05-31 18:46 UTC, galeal2 commented
I changed some variables' names, added docstring (i am not sure if that is right, I have never used it before) and I created different files for the Node class and BST class.
Thank you

2017-05-31 21:41 UTC, ariava approved these changes
Looks great! Well done!

2017-06-07 08:16 UTC, merged